import { Pool, type PoolClient } from "pg";
import type { HubAuditPage, HubBootstrapResult, HubDevice, HubDeviceCredential, HubMember, SyncPullPackage, SyncPushResult } from "@bubu/contracts";
import { HubAuthority, type HubAuthorityOptions, type HubAuthorityState } from "./authority.js";

interface PostgresAuthorityOptions extends Omit<HubAuthorityOptions, "statePath" | "initialState"> { readonly tableName?: string; readonly ownsPool?: boolean }
const tableNamePattern = /^[a-z][a-z0-9_]{0,62}$/u;
const emptyState = (): HubAuthorityState => ({ version: 1, tenants: [] });
export function validatePostgresConnectionString(value: string): string { const parsed = new URL(value); if (parsed.protocol !== "postgres:" && parsed.protocol !== "postgresql:") throw new Error("BUBU_HUB_DATABASE_URL must use PostgreSQL"); const socketHost = parsed.searchParams.get("host")?.startsWith("/") === true; const loopback = parsed.hostname === "" || parsed.hostname === "localhost" || parsed.hostname === "127.0.0.1" || parsed.hostname === "[::1]"; const sslMode = parsed.searchParams.get("sslmode"); if (!socketHost && !loopback && sslMode !== "require" && sslMode !== "verify-ca" && sslMode !== "verify-full") throw new Error("Remote PostgreSQL Hub storage requires TLS"); return value; }

export class PostgresHubAuthority {
  readonly #pool: Pool; readonly #options: PostgresAuthorityOptions; readonly #tableName: string; readonly #table: string;
  constructor(pool: Pool, options: PostgresAuthorityOptions = {}) { const table = options.tableName ?? "bubu_hub_authority_state"; if (!tableNamePattern.test(table)) throw new Error("PostgreSQL Hub table name is invalid"); this.#pool = pool; this.#options = options; this.#tableName = table; this.#table = `"${table}"`; }
  static async connect(connectionString: string, options: Omit<PostgresAuthorityOptions, "ownsPool"> = {}): Promise<PostgresHubAuthority> { const pool = new Pool({ connectionString: validatePostgresConnectionString(connectionString), max: 10, connectionTimeoutMillis: 10_000, idleTimeoutMillis: 30_000 }); const authority = new PostgresHubAuthority(pool, { ...options, ownsPool: true }); try { await authority.initialize(); return authority; } catch (error) { await pool.end(); throw error; } }
  async initialize(initialState: unknown = emptyState()): Promise<boolean> { const validatedState = new HubAuthority({ initialState }).snapshot(); const client = await this.#pool.connect(); try { await client.query(`CREATE TABLE IF NOT EXISTS ${this.#table} (singleton smallint PRIMARY KEY CHECK (singleton = 1), schema_version integer NOT NULL CHECK (schema_version = 1), revision bigint NOT NULL DEFAULT 0, state_json jsonb NOT NULL, updated_at timestamptz NOT NULL DEFAULT now())`); const inserted = await client.query(`INSERT INTO ${this.#table}(singleton, schema_version, state_json) VALUES (1, 1, $1::jsonb) ON CONFLICT (singleton) DO NOTHING`, [JSON.stringify(validatedState)]); return inserted.rowCount === 1; } finally { client.release(); } }
  async #run<T>(operation: (authority: HubAuthority) => T): Promise<T> { for (let attempt = 1; attempt <= 3; attempt++) { try { return await this.#attempt(operation); } catch (error) { const code = typeof error === "object" && error !== null && "code" in error ? (error as { code?: unknown }).code : undefined; if ((code !== "40001" && code !== "40P01") || attempt === 3) throw error; } } throw new Error("PostgreSQL Hub transaction retry budget was exhausted"); }
  async #attempt<T>(operation: (authority: HubAuthority) => T): Promise<T> { const client = await this.#pool.connect(); let locked = false; let began = false; let discardClient = false; try { await client.query("SELECT pg_advisory_lock($1::integer, hashtext($2))", [1_112_884_812, this.#tableName]); locked = true; await client.query("BEGIN ISOLATION LEVEL SERIALIZABLE"); began = true; const result = await client.query<{ state_json: HubAuthorityState | string }>(`SELECT state_json FROM ${this.#table} WHERE singleton = 1 FOR UPDATE`); const stored = result.rows[0]?.state_json; if (stored === undefined) throw new Error("PostgreSQL Hub state row is missing"); const state = typeof stored === "string" ? JSON.parse(stored) as unknown : stored; const authority = new HubAuthority({ initialState: state, ...(this.#options.now ? { now: this.#options.now } : {}), ...(this.#options.randomId ? { randomId: this.#options.randomId } : {}), ...(this.#options.randomToken ? { randomToken: this.#options.randomToken } : {}), ...(this.#options.limits ? { limits: this.#options.limits } : {}) }); const value = operation(authority); await client.query(`UPDATE ${this.#table} SET state_json = $1::jsonb, revision = revision + 1, updated_at = now() WHERE singleton = 1`, [JSON.stringify(authority.snapshot())]); await client.query("COMMIT"); began = false; return value; } catch (error) { if (began) await this.#rollback(client); throw error; } finally { if (locked) { try { await client.query("SELECT pg_advisory_unlock($1::integer, hashtext($2))", [1_112_884_812, this.#tableName]); } catch { discardClient = true; } } client.release(discardClient); } }
  async #rollback(client: PoolClient): Promise<void> { try { await client.query("ROLLBACK"); } catch { /* The original authority or database error remains primary. */ } }
  bootstrap(value: unknown): Promise<HubBootstrapResult> { return this.#run((authority) => authority.bootstrap(value)); }
  createMember(token: string, value: unknown): Promise<HubMember> { return this.#run((authority) => authority.createMember(token, value)); }
  createDevice(token: string, value: unknown): Promise<HubDeviceCredential> { return this.#run((authority) => authority.createDevice(token, value)); }
  revokeMember(token: string, memberId: string): Promise<HubMember> { return this.#run((authority) => authority.revokeMember(token, memberId)); }
  revokeDevice(token: string, deviceId: string): Promise<HubDevice> { return this.#run((authority) => authority.revokeDevice(token, deviceId)); }
  push(token: string, value: unknown): Promise<SyncPushResult> { return this.#run((authority) => authority.push(token, value)); }
  pull(token: string, value: unknown): Promise<SyncPullPackage> { return this.#run((authority) => authority.pull(token, value)); }
  audit(token: string): Promise<HubAuditPage> { return this.#run((authority) => authority.audit(token)); }
  async close(): Promise<void> { if (this.#options.ownsPool) await this.#pool.end(); }
}
