import { z } from "zod";
import { datasetIdSchema } from "./dataset.js";
import { operationIdSchema } from "./operation.js";

export const hubRoleSchema = z.enum(["owner", "editor", "viewer", "auditor"]);
export const hubPermissionSchema = z.enum(["tenant:manage", "member:manage", "device:manage", "sync:read", "sync:write", "audit:read"]);
export const hubTenantSchema = z.object({ schemaVersion: z.literal(1), id: datasetIdSchema, name: z.string().trim().min(1).max(100), createdAt: z.string().datetime({ offset: true }) }).strict();
export const hubMemberSchema = z.object({ schemaVersion: z.literal(1), id: datasetIdSchema, tenantId: datasetIdSchema, displayName: z.string().trim().min(1).max(100), role: hubRoleSchema, status: z.enum(["active", "revoked"]), createdAt: z.string().datetime({ offset: true }), revokedAt: z.string().datetime({ offset: true }).nullable() }).strict();
export const hubDeviceSchema = z.object({ schemaVersion: z.literal(1), id: datasetIdSchema, tenantId: datasetIdSchema, memberId: datasetIdSchema, name: z.string().trim().min(1).max(100), tokenFingerprint: z.string().regex(/^[a-f0-9]{64}$/u), status: z.enum(["active", "revoked"]), createdAt: z.string().datetime({ offset: true }), revokedAt: z.string().datetime({ offset: true }).nullable() }).strict();
export const hubBootstrapInputSchema = z.object({ tenantName: z.string().trim().min(1).max(100), ownerName: z.string().trim().min(1).max(100), deviceName: z.string().trim().min(1).max(100) }).strict();
export const hubBootstrapResultSchema = z.object({ tenant: hubTenantSchema, member: hubMemberSchema, device: hubDeviceSchema, deviceToken: z.string().min(32).max(512), auditVerificationKey: z.string().regex(/^[A-Za-z0-9_-]{32,512}$/u) }).strict();
export const hubMemberCreateInputSchema = z.object({ displayName: z.string().trim().min(1).max(100), role: hubRoleSchema.exclude(["owner"]) }).strict();
export const hubDeviceCreateInputSchema = z.object({ memberId: datasetIdSchema, name: z.string().trim().min(1).max(100) }).strict();
export const hubDeviceCredentialSchema = z.object({ device: hubDeviceSchema, deviceToken: z.string().min(32).max(512) }).strict();

export const syncObjectKindSchema = z.enum(["workflow-definition", "reconciliation-definition", "report-evidence", "knowledge-metadata"]);
const encryptedPayloadSchema = z.object({ algorithm: z.literal("aes-256-gcm"), keyId: datasetIdSchema, nonce: z.string().regex(/^[A-Za-z0-9_-]{16}$/u), ciphertext: z.string().regex(/^[A-Za-z0-9_-]{1,349526}$/u), contentSha256: z.string().regex(/^[a-f0-9]{64}$/u) }).strict();
export const syncPushOperationSchema = z.object({ schemaVersion: z.literal(1), operationId: operationIdSchema, tenantId: datasetIdSchema, deviceId: datasetIdSchema, objectId: datasetIdSchema, objectKind: syncObjectKindSchema, baseVersion: z.number().int().positive().nullable(), objectVersion: z.number().int().positive(), deleted: z.boolean(), payload: encryptedPayloadSchema.nullable(), createdAt: z.string().datetime({ offset: true }) }).strict().superRefine((value, context) => {
  if (value.deleted === (value.payload !== null)) context.addIssue({ code: "custom", message: "Deleted sync operations cannot carry payload and live operations require payload" });
  if (value.baseVersion === null ? value.objectVersion !== 1 : value.objectVersion !== value.baseVersion + 1) context.addIssue({ code: "custom", message: "Sync object versions must advance exactly once" });
});
export const syncObjectVersionSchema = z.object({ schemaVersion: z.literal(1), operationId: operationIdSchema, tenantId: datasetIdSchema, deviceId: datasetIdSchema, objectId: datasetIdSchema, objectKind: syncObjectKindSchema, objectVersion: z.number().int().positive(), deleted: z.boolean(), payload: encryptedPayloadSchema.nullable(), createdAt: z.string().datetime({ offset: true }), sequence: z.number().int().positive(), acceptedAt: z.string().datetime({ offset: true }) }).strict().superRefine((value, context) => { if (value.deleted === (value.payload !== null)) context.addIssue({ code: "custom", message: "Deleted sync versions cannot carry payload and live versions require payload" }); });
export const syncConflictSchema = z.object({ status: z.literal("conflict"), objectId: datasetIdSchema, attemptedBaseVersion: z.number().int().positive().nullable(), currentVersion: z.number().int().positive().nullable(), currentSequence: z.number().int().nonnegative() }).strict();
export const syncPushAcceptedSchema = z.object({ status: z.literal("accepted"), operationId: operationIdSchema, objectId: datasetIdSchema, objectVersion: z.number().int().positive(), sequence: z.number().int().positive(), idempotent: z.boolean() }).strict();
export const syncPushResultSchema = z.discriminatedUnion("status", [syncPushAcceptedSchema, syncConflictSchema]);
export const syncPullRequestSchema = z.object({ schemaVersion: z.literal(1), tenantId: datasetIdSchema, deviceId: datasetIdSchema, afterSequence: z.number().int().nonnegative(), limit: z.number().int().min(1).max(100) }).strict();
export const syncPullPackageSchema = z.object({ schemaVersion: z.literal(1), tenantId: datasetIdSchema, afterSequence: z.number().int().nonnegative(), nextSequence: z.number().int().nonnegative(), hasMore: z.boolean(), objects: z.array(syncObjectVersionSchema).max(100) }).strict();

export const hubAuditActionSchema = z.enum(["tenant-created", "member-created", "member-revoked", "device-created", "device-revoked", "object-pushed", "object-deleted", "sync-conflict"]);
export const hubAuditEventSchema = z.object({ schemaVersion: z.literal(1), tenantId: datasetIdSchema, sequence: z.number().int().positive(), action: hubAuditActionSchema, actorDeviceId: datasetIdSchema, subjectId: datasetIdSchema, objectVersion: z.number().int().positive().nullable(), occurredAt: z.string().datetime({ offset: true }), previousHash: z.string().regex(/^[a-f0-9]{64}$/u), eventHash: z.string().regex(/^[a-f0-9]{64}$/u), signature: z.string().regex(/^[a-f0-9]{128}$/u) }).strict();
export const hubAuditPageSchema = z.object({ schemaVersion: z.literal(1), tenantId: datasetIdSchema, events: z.array(hubAuditEventSchema).max(500) }).strict();
const hubBaseUrlSchema = z.string().url().max(2_048).superRefine((value, context) => { const url = new URL(value); if (url.protocol !== "https:" || url.username || url.password || url.hash || url.pathname !== "/" || url.search) context.addIssue({ code: "custom", message: "Hub URL must be a credential-free HTTPS origin" }); });
export const hubConnectionInputSchema = z.object({ baseUrl: hubBaseUrlSchema, tenantId: datasetIdSchema, deviceId: datasetIdSchema, role: hubRoleSchema, deviceToken: z.string().min(32).max(512), contentKey: z.string().regex(/^[A-Za-z0-9_-]{43}$/u), auditVerificationKey: z.string().regex(/^[A-Za-z0-9_-]{32,512}$/u) }).strict();
export const hubConnectionProfileSchema = z.object({ baseUrl: hubBaseUrlSchema, tenantId: datasetIdSchema, deviceId: datasetIdSchema, role: hubRoleSchema, configured: z.literal(true), encryptionAvailable: z.boolean() }).strict();
export const hubBootstrapRequestSchema = z.object({ baseUrl: hubBaseUrlSchema, tenantName: z.string().trim().min(1).max(100), ownerName: z.string().trim().min(1).max(100), deviceName: z.string().trim().min(1).max(100) }).strict();
export const localSyncQueueItemSchema = z.object({ id: datasetIdSchema, objectId: datasetIdSchema, objectKind: syncObjectKindSchema, objectVersion: z.number().int().positive(), status: z.enum(["pending", "syncing", "succeeded", "conflict", "failed", "discarded"]), attempts: z.number().int().min(0).max(3), createdAt: z.string().datetime({ offset: true }), completedAt: z.string().datetime({ offset: true }).nullable(), errorCode: z.string().regex(/^[A-Z][A-Z0-9_]{0,63}$/u).nullable(), conflict: syncConflictSchema.nullable() }).strict();
export const localSyncQueueSchema = z.array(localSyncQueueItemSchema).max(500);
export const localSyncedObjectSchema = z.object({ objectId: datasetIdSchema, objectKind: syncObjectKindSchema, objectVersion: z.number().int().positive(), sequence: z.number().int().positive(), deleted: z.boolean(), receivedAt: z.string().datetime({ offset: true }) }).strict();
export const localSyncedObjectsSchema = z.array(localSyncedObjectSchema).max(500);
export const localSyncedObjectPreviewSchema = z.object({ object: localSyncedObjectSchema, contentJson: z.string().min(2).max(262_144), contentSha256: z.string().regex(/^[a-f0-9]{64}$/u) }).strict();
export const hubQueueWorkflowRequestSchema = z.object({ workflowId: datasetIdSchema, target: z.discriminatedUnion("kind", [z.object({ kind: z.literal("dataset"), id: datasetIdSchema }).strict(), z.object({ kind: z.literal("group"), id: datasetIdSchema }).strict()]) }).strict();
export const hubResolveConflictInputSchema = z.object({ queueId: datasetIdSchema, decision: z.enum(["accept-remote", "retry-local"]) }).strict();
export const hubQueueDeleteInputSchema = z.object({ objectId: datasetIdSchema, objectKind: syncObjectKindSchema }).strict();
export const hubApplyRemoteObjectInputSchema = z.object({ objectId: datasetIdSchema, objectVersion: z.number().int().positive(), expectedContentSha256: z.string().regex(/^[a-f0-9]{64}$/u), decision: z.enum(["apply-if-absent-or-identical", "replace-reviewed-workflow"]) }).strict();
export const hubAppliedObjectReceiptSchema = z.object({ schemaVersion: z.literal(1), objectId: datasetIdSchema, objectKind: z.literal("workflow-definition"), objectVersion: z.number().int().positive(), remoteSequence: z.number().int().positive(), contentSha256: z.string().regex(/^[a-f0-9]{64}$/u), localWorkflowVersion: z.number().int().positive(), localDisposition: z.enum(["created", "identical", "replaced"]), appliedAt: z.string().datetime({ offset: true }) }).strict();
export const hubAppliedObjectReceiptsSchema = z.array(hubAppliedObjectReceiptSchema).max(500);

export type HubRole = z.infer<typeof hubRoleSchema>; export type HubPermission = z.infer<typeof hubPermissionSchema>; export type HubTenant = z.infer<typeof hubTenantSchema>; export type HubMember = z.infer<typeof hubMemberSchema>; export type HubDevice = z.infer<typeof hubDeviceSchema>; export type HubBootstrapInput = z.infer<typeof hubBootstrapInputSchema>; export type HubBootstrapResult = z.infer<typeof hubBootstrapResultSchema>; export type HubMemberCreateInput = z.infer<typeof hubMemberCreateInputSchema>; export type HubDeviceCreateInput = z.infer<typeof hubDeviceCreateInputSchema>; export type HubDeviceCredential = z.infer<typeof hubDeviceCredentialSchema>; export type SyncObjectKind = z.infer<typeof syncObjectKindSchema>; export type SyncPushOperation = z.infer<typeof syncPushOperationSchema>; export type SyncObjectVersion = z.infer<typeof syncObjectVersionSchema>; export type SyncPushResult = z.infer<typeof syncPushResultSchema>; export type SyncPullRequest = z.infer<typeof syncPullRequestSchema>; export type SyncPullPackage = z.infer<typeof syncPullPackageSchema>; export type HubAuditAction = z.infer<typeof hubAuditActionSchema>; export type HubAuditEvent = z.infer<typeof hubAuditEventSchema>; export type HubAuditPage = z.infer<typeof hubAuditPageSchema>;
export type HubConnectionInput = z.infer<typeof hubConnectionInputSchema>; export type HubConnectionProfile = z.infer<typeof hubConnectionProfileSchema>; export type HubBootstrapRequest = z.infer<typeof hubBootstrapRequestSchema>; export type LocalSyncQueueItem = z.infer<typeof localSyncQueueItemSchema>; export type LocalSyncedObject = z.infer<typeof localSyncedObjectSchema>;
export type LocalSyncedObjectPreview = z.infer<typeof localSyncedObjectPreviewSchema>;
export type HubQueueWorkflowRequest = z.infer<typeof hubQueueWorkflowRequestSchema>;
export type HubResolveConflictInput = z.infer<typeof hubResolveConflictInputSchema>; export type HubQueueDeleteInput = z.infer<typeof hubQueueDeleteInputSchema>;
export type HubApplyRemoteObjectInput = z.infer<typeof hubApplyRemoteObjectInputSchema>; export type HubAppliedObjectReceipt = z.infer<typeof hubAppliedObjectReceiptSchema>;
export const parseHubBootstrapInput = (value: unknown): HubBootstrapInput => hubBootstrapInputSchema.parse(value); export const parseHubBootstrapResult = (value: unknown): HubBootstrapResult => hubBootstrapResultSchema.parse(value); export const parseHubMemberCreateInput = (value: unknown): HubMemberCreateInput => hubMemberCreateInputSchema.parse(value); export const parseHubDeviceCreateInput = (value: unknown): HubDeviceCreateInput => hubDeviceCreateInputSchema.parse(value); export const parseHubDeviceCredential = (value: unknown): HubDeviceCredential => hubDeviceCredentialSchema.parse(value); export const parseSyncPushOperation = (value: unknown): SyncPushOperation => syncPushOperationSchema.parse(value); export const parseSyncPushResult = (value: unknown): SyncPushResult => syncPushResultSchema.parse(value); export const parseSyncPullRequest = (value: unknown): SyncPullRequest => syncPullRequestSchema.parse(value); export const parseSyncPullPackage = (value: unknown): SyncPullPackage => syncPullPackageSchema.parse(value); export const parseHubAuditPage = (value: unknown): HubAuditPage => hubAuditPageSchema.parse(value);
export const parseHubConnectionInput = (value: unknown): HubConnectionInput => hubConnectionInputSchema.parse(value); export const parseHubConnectionProfile = (value: unknown): HubConnectionProfile => hubConnectionProfileSchema.parse(value); export const parseHubBootstrapRequest = (value: unknown): HubBootstrapRequest => hubBootstrapRequestSchema.parse(value); export const parseLocalSyncQueue = (value: unknown): readonly LocalSyncQueueItem[] => localSyncQueueSchema.parse(value); export const parseLocalSyncedObjects = (value: unknown): readonly LocalSyncedObject[] => localSyncedObjectsSchema.parse(value);
export const parseLocalSyncedObjectPreview = (value: unknown): LocalSyncedObjectPreview => localSyncedObjectPreviewSchema.parse(value);
export const parseHubQueueWorkflowRequest = (value: unknown): HubQueueWorkflowRequest => hubQueueWorkflowRequestSchema.parse(value);
export const parseHubResolveConflictInput = (value: unknown): HubResolveConflictInput => hubResolveConflictInputSchema.parse(value); export const parseHubQueueDeleteInput = (value: unknown): HubQueueDeleteInput => hubQueueDeleteInputSchema.parse(value);
export const parseHubApplyRemoteObjectInput = (value: unknown): HubApplyRemoteObjectInput => hubApplyRemoteObjectInputSchema.parse(value); export const parseHubAppliedObjectReceipt = (value: unknown): HubAppliedObjectReceipt => hubAppliedObjectReceiptSchema.parse(value); export const parseHubAppliedObjectReceipts = (value: unknown): readonly HubAppliedObjectReceipt[] => hubAppliedObjectReceiptsSchema.parse(value);
