import { useEffect, useState } from "react";
import type { HubAppliedObjectReceipt, HubConnectionProfile, LocalSyncQueueItem, LocalSyncedObject, LocalSyncedObjectPreview } from "../shared/product-api.js";
import { operationErrorMessage } from "./operation.js";

export function HubSettings() {
  const [profile, setProfile] = useState<HubConnectionProfile | null>();
  const [queue, setQueue] = useState<readonly LocalSyncQueueItem[]>([]);
  const [objects, setObjects] = useState<readonly LocalSyncedObject[]>([]);
  const [preview, setPreview] = useState<LocalSyncedObjectPreview>();
  const [applications, setApplications] = useState<readonly HubAppliedObjectReceipt[]>([]);
  const [notice, setNotice] = useState<string>(); const [audit, setAudit] = useState<string>();
  const [baseUrl, setBaseUrl] = useState(""); const [tenantName, setTenantName] = useState(""); const [ownerName, setOwnerName] = useState(""); const [deviceName, setDeviceName] = useState("");
  const [tenantId, setTenantId] = useState(""); const [deviceId, setDeviceId] = useState(""); const [role, setRole] = useState<"owner" | "editor" | "viewer" | "auditor">("editor"); const [deviceToken, setDeviceToken] = useState(""); const [contentKey, setContentKey] = useState(""); const [auditKey, setAuditKey] = useState("");

  async function load(): Promise<void> { const [nextProfile, nextQueue, nextObjects, nextApplications] = await Promise.all([window.bubu.hub.profile(), window.bubu.hub.queue(), window.bubu.hub.objects(), window.bubu.hub.applications()]); setProfile(nextProfile); setQueue(nextQueue); setObjects(nextObjects); setApplications(nextApplications); }
  useEffect(() => { void load().catch((error: unknown) => setNotice(operationErrorMessage(error, "读取 Hub 状态失败"))); }, []);
  async function bootstrap(): Promise<void> { try { setProfile(await window.bubu.hub.bootstrap({ baseUrl, tenantName, ownerName, deviceName })); setNotice("租户与本设备已在所选 Hub 创建；设备 token 和内容密钥只加密保存在本机。"); } catch (error) { setNotice(operationErrorMessage(error, "创建 Hub 租户失败")); } }
  async function configure(): Promise<void> { try { setProfile(await window.bubu.hub.configure({ baseUrl, tenantId, deviceId, role, deviceToken, contentKey, auditVerificationKey: auditKey })); setNotice("现有 Hub 设备已配置；尚未发送或拉取对象。"); } catch (error) { setNotice(operationErrorMessage(error, "配置 Hub 设备失败")); } }
  async function flush(): Promise<void> { try { setQueue(await window.bubu.hub.flush()); setNotice("已处理当前有界 outbox；冲突不会自动覆盖远端版本。"); } catch (error) { setNotice(operationErrorMessage(error, "Hub 当前不可用；outbox 已保留")); } }
  async function pull(): Promise<void> { try { setObjects(await window.bubu.hub.pull()); setNotice("已拉取加密对象版本；未自动改写本地数据权威。"); } catch (error) { setNotice(operationErrorMessage(error, "拉取 Hub 对象失败")); } }
  async function resolveConflict(item: LocalSyncQueueItem, decision: "accept-remote" | "retry-local"): Promise<void> { try { await window.bubu.hub.resolveConflict({ queueId: item.id, decision }); setQueue(await window.bubu.hub.queue()); setNotice(decision === "accept-remote" ? "已明确保留远端版本；本地冲突写入已丢弃并保留证据。" : "已把本地加密对象重建为基于当前远端版本的新写入。"); } catch (error) { setNotice(operationErrorMessage(error, "解决同步冲突失败")); } }
  async function applyPreview(decision: "apply-if-absent-or-identical" | "replace-reviewed-workflow"): Promise<void> { if (!preview) return; try { const receipt = await window.bubu.hub.apply({ objectId: preview.object.objectId, objectVersion: preview.object.objectVersion, expectedContentSha256: preview.contentSha256, decision }); setApplications(await window.bubu.hub.applications()); setNotice(`已${receipt.localDisposition === "replaced" ? "替换" : receipt.localDisposition === "created" ? "创建" : "确认相同"}本地工作流 v${receipt.localWorkflowVersion}；精确摘要和远端版本证据已保存。`); } catch (error) { setNotice(operationErrorMessage(error, "远端工作流未应用")); } }

  return <section className="hub-settings" aria-label="可选 Hub 与同步">
    <header className="settings-section-header"><div><p className="hero-kicker">可选协作</p><h3>Hub、RBAC 与加密 Sync</h3></div><span>{profile ? profile.role : "本地模式"}</span></header>
    <div className="security-warning">Hub 永远不是本地启动依赖。只同步用户明确选择并在本机 AES-256-GCM 加密的产品对象；原始行、凭证、本地路径和内容密钥不会进入 Hub。拉取只进入加密收件箱；应用工作流必须审查精确摘要且本地目标与线程一致。冲突必须人工处理，不做 last-write-wins。</div>
    {notice && <p role="status">{notice}</p>}
    {!profile && <div className="remote-mcp-grid">
      <form onSubmit={(event) => { event.preventDefault(); void bootstrap(); }}><h4>创建新租户与 owner 设备</h4><label><span>Hub HTTPS origin</span><input required type="url" value={baseUrl} onChange={(event) => setBaseUrl(event.target.value)} placeholder="https://hub.example.com/" /></label><label><span>租户名称</span><input required value={tenantName} onChange={(event) => setTenantName(event.target.value)} /></label><label><span>Owner 名称</span><input required value={ownerName} onChange={(event) => setOwnerName(event.target.value)} /></label><label><span>设备名称</span><input required value={deviceName} onChange={(event) => setDeviceName(event.target.value)} /></label><button type="submit">明确创建远程租户</button></form>
      <form onSubmit={(event) => { event.preventDefault(); void configure(); }}><h4>连接已获授权的设备</h4><label><span>Tenant ID</span><input required pattern="[a-f0-9]{32}" value={tenantId} onChange={(event) => setTenantId(event.target.value)} /></label><label><span>Device ID</span><input required pattern="[a-f0-9]{32}" value={deviceId} onChange={(event) => setDeviceId(event.target.value)} /></label><label><span>角色</span><select value={role} onChange={(event) => setRole(event.target.value as typeof role)}><option value="owner">owner</option><option value="editor">editor</option><option value="viewer">viewer</option><option value="auditor">auditor</option></select></label><label><span>一次交付的 device token</span><input required type="password" value={deviceToken} onChange={(event) => setDeviceToken(event.target.value)} /></label><label><span>共享内容密钥</span><input required type="password" value={contentKey} onChange={(event) => setContentKey(event.target.value)} /></label><label><span>审计公钥</span><input required value={auditKey} onChange={(event) => setAuditKey(event.target.value)} /></label><button type="submit">只保存加密配置</button></form>
    </div>}
    {profile && <><dl><div><dt>Hub</dt><dd><code>{profile.baseUrl}</code></dd></div><div><dt>Tenant / Device</dt><dd><code>{profile.tenantId.slice(0, 8)}… / {profile.deviceId.slice(0, 8)}…</code></dd></div><div><dt>本地权限预检</dt><dd>{profile.role}</dd></div></dl><div className="plan-actions">{(profile.role === "owner" || profile.role === "editor") && <button type="button" onClick={() => void flush()}>重放 outbox</button>}{profile.role !== "auditor" && <button type="button" onClick={() => void pull()}>拉取加密版本</button>}{(profile.role === "owner" || profile.role === "auditor") && <button type="button" onClick={() => void window.bubu.hub.audit().then((result) => setAudit(result.verified ? `签名链已验证 · ${result.page.events.length} 条` : "签名链验证失败"), (error: unknown) => setNotice(operationErrorMessage(error, "验证集中审计失败")))}>验证集中审计</button>}<button type="button" className="danger-action" onClick={() => void window.bubu.hub.disconnect().then(() => setProfile(null))}>断开本设备</button></div>{audit && <p>{audit}</p>}
      <section><h4>Outbox</h4>{queue.length === 0 ? <p>暂无明确选择的待同步对象。</p> : queue.map((item) => <div key={item.id}><p>{item.objectKind} · v{item.objectVersion} · {item.status} · {item.attempts}/3{item.conflict ? ` · 远端 v${item.conflict.currentVersion ?? "已删除"}` : ""}</p>{item.status === "conflict" && <div className="plan-actions"><button type="button" onClick={() => void resolveConflict(item, "accept-remote")}>保留远端版本</button><button type="button" onClick={() => void resolveConflict(item, "retry-local")}>基于远端重试本地版本</button></div>}{item.status === "succeeded" && item.errorCode === null && <button type="button" className="danger-action" onClick={() => void window.bubu.hub.deleteObject({ objectId: item.objectId, objectKind: item.objectKind }).then(() => window.bubu.hub.queue().then(setQueue))}>创建删除墓碑</button>}</div>)}</section>
      <section><h4>收到的不可变版本</h4>{objects.length === 0 ? <p>尚未拉取对象。</p> : objects.map((object) => <button type="button" key={`${object.objectId}:${object.objectVersion}`} onClick={() => void window.bubu.hub.inspect(object.objectId, object.objectVersion).then(setPreview)}>{object.objectKind} · v{object.objectVersion}{object.deleted ? " · 已删除" : ""}</button>)}</section>{preview && <article><strong>解密审查 · 摘要 {preview.contentSha256.slice(0, 12)}…</strong><pre>{preview.contentJson}</pre>{preview.object.objectKind === "workflow-definition" && !preview.object.deleted && <div className="plan-actions"><button type="button" onClick={() => void applyPreview("apply-if-absent-or-identical")}>仅新增或确认相同版本</button><button type="button" className="danger-action" onClick={() => void applyPreview("replace-reviewed-workflow")}>明确替换同 ID 本地工作流</button></div>}</article>}{applications.length > 0 && <p>本机已保存 {applications.length} 条远端应用证据；重复请求不会再次增加本地版本。</p>}
    </>}
  </section>;
}
