// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplicationMenu() {
  return window['go']['main']['App']['ApplicationMenu']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearAllCache() {
  return window['go']['main']['App']['ClearAllCache']();
}

export function ClearCacheByType(arg1) {
  return window['go']['main']['App']['ClearCacheByType'](arg1);
}

export function CreateConversation(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateConversation'](arg1, arg2, arg3);
}

export function CreateConversationsForFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateConversationsForFiles'](arg1, arg2, arg3);
}

export function DeleteTemplate(arg1) {
  return window['go']['main']['App']['DeleteTemplate'](arg1);
}

export function ExecuteCommand(arg1, arg2) {
  return window['go']['main']['App']['ExecuteCommand'](arg1, arg2);
}

export function ExecuteNaturalLanguageQuery(arg1) {
  return window['go']['main']['App']['ExecuteNaturalLanguageQuery'](arg1);
}

export function ExecuteSQL(arg1) {
  return window['go']['main']['App']['ExecuteSQL'](arg1);
}

export function ExecuteTemplateSQL(arg1, arg2) {
  return window['go']['main']['App']['ExecuteTemplateSQL'](arg1, arg2);
}

export function ExportToExcel(arg1) {
  return window['go']['main']['App']['ExportToExcel'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetCacheStats() {
  return window['go']['main']['App']['GetCacheStats']();
}

export function GetConversation(arg1) {
  return window['go']['main']['App']['GetConversation'](arg1);
}

export function GetConversationMessages(arg1) {
  return window['go']['main']['App']['GetConversationMessages'](arg1);
}

export function GetConversationsByFileKey(arg1) {
  return window['go']['main']['App']['GetConversationsByFileKey'](arg1);
}

export function GetConversationsByFiles(arg1) {
  return window['go']['main']['App']['GetConversationsByFiles'](arg1);
}

export function GetInstallationInfo() {
  return window['go']['main']['App']['GetInstallationInfo']();
}

export function GetLLMConfig() {
  return window['go']['main']['App']['GetLLMConfig']();
}

export function GetLLMTimeout() {
  return window['go']['main']['App']['GetLLMTimeout']();
}

export function GetPopularQueries(arg1, arg2) {
  return window['go']['main']['App']['GetPopularQueries'](arg1, arg2);
}

export function GetQueryHistory() {
  return window['go']['main']['App']['GetQueryHistory']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetTableColumns(arg1) {
  return window['go']['main']['App']['GetTableColumns'](arg1);
}

export function GetTableData(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableData'](arg1, arg2, arg3);
}

export function GetTableList() {
  return window['go']['main']['App']['GetTableList']();
}

export function GetTableSchema(arg1) {
  return window['go']['main']['App']['GetTableSchema'](arg1);
}

export function GetTemplatesByFiles(arg1) {
  return window['go']['main']['App']['GetTemplatesByFiles'](arg1);
}

export function GetUploadedFiles() {
  return window['go']['main']['App']['GetUploadedFiles']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ManualCleanExpiredCache() {
  return window['go']['main']['App']['ManualCleanExpiredCache']();
}

export function ProcessNaturalLanguage(arg1) {
  return window['go']['main']['App']['ProcessNaturalLanguage'](arg1);
}

export function ProcessNaturalLanguageEnhanced(arg1) {
  return window['go']['main']['App']['ProcessNaturalLanguageEnhanced'](arg1);
}

export function ProcessNaturalLanguageWithFiles(arg1, arg2) {
  return window['go']['main']['App']['ProcessNaturalLanguageWithFiles'](arg1, arg2);
}

export function ReloadConfig() {
  return window['go']['main']['App']['ReloadConfig']();
}

export function RestartApplication() {
  return window['go']['main']['App']['RestartApplication']();
}

export function SaveConversationMessage(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['SaveConversationMessage'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function SaveTemplate(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveTemplate'](arg1, arg2, arg3, arg4, arg5);
}

export function SetInstanceManager(arg1) {
  return window['go']['main']['App']['SetInstanceManager'](arg1);
}

export function SetLLMAPIKey(arg1) {
  return window['go']['main']['App']['SetLLMAPIKey'](arg1);
}

export function SetLLMModel(arg1) {
  return window['go']['main']['App']['SetLLMModel'](arg1);
}

export function SetLLMTimeout(arg1) {
  return window['go']['main']['App']['SetLLMTimeout'](arg1);
}

export function ShowErrorNotification(arg1) {
  return window['go']['main']['App']['ShowErrorNotification'](arg1);
}

export function ShowNotification(arg1, arg2) {
  return window['go']['main']['App']['ShowNotification'](arg1, arg2);
}

export function ShowSuccessNotification(arg1) {
  return window['go']['main']['App']['ShowSuccessNotification'](arg1);
}

export function ToggleWindow() {
  return window['go']['main']['App']['ToggleWindow']();
}

export function UpdateConversationTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateConversationTitle'](arg1, arg2);
}

export function UpdateTemplate(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateTemplate'](arg1, arg2, arg3, arg4, arg5);
}

export function UploadFile(arg1, arg2) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2);
}

export function UseTemplate(arg1) {
  return window['go']['main']['App']['UseTemplate'](arg1);
}
