// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {menu} from '../models';
import {main} from '../models';

export function ApplicationMenu():Promise<menu.Menu>;

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function ClearAllCache():Promise<void>;

export function ClearCacheByType(arg1:string):Promise<void>;

export function CreateConversation(arg1:string,arg2:string,arg3:string):Promise<main.Conversation>;

export function CreateConversationsForFiles(arg1:string,arg2:Array<string>,arg3:string):Promise<Array<main.Conversation>>;

export function DeleteTemplate(arg1:number):Promise<void>;

export function ExecuteCommand(arg1:string,arg2:Array<string>):Promise<void>;

export function ExecuteNaturalLanguageQuery(arg1:string):Promise<main.QueryResult>;

export function ExecuteSQL(arg1:string):Promise<main.QueryResult>;

export function ExecuteTemplateSQL(arg1:string,arg2:Array<string>):Promise<main.LLMProcessResult>;

export function ExportToExcel(arg1:string):Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetCacheStats():Promise<Record<string, any>>;

export function GetConversation(arg1:string):Promise<main.Conversation>;

export function GetConversationMessages(arg1:number):Promise<Array<main.ConversationMessage>>;

export function GetConversationsByFileKey(arg1:string):Promise<Array<main.Conversation>>;

export function GetConversationsByFiles(arg1:Array<string>):Promise<Array<main.Conversation>>;

export function GetInstallationInfo():Promise<main.InstallationInfo>;

export function GetLLMConfig():Promise<Record<string, any>>;

export function GetLLMTimeout():Promise<number>;

export function GetPopularQueries(arg1:string,arg2:number):Promise<Array<main.PromptSQLMapping>>;

export function GetQueryHistory():Promise<Array<main.QueryHistory>>;

export function GetSystemInfo():Promise<main.SystemInfo>;

export function GetTableColumns(arg1:string):Promise<Array<string>>;

export function GetTableData(arg1:string,arg2:number,arg3:number):Promise<main.QueryResult>;

export function GetTableList():Promise<Array<string>>;

export function GetTableSchema(arg1:string):Promise<main.QueryResult>;

export function GetTemplatesByFiles(arg1:Array<string>):Promise<Array<main.SavedTemplate>>;

export function GetUploadedFiles():Promise<Array<main.File>>;

export function Greet(arg1:string):Promise<string>;

export function ManualCleanExpiredCache():Promise<void>;

export function ProcessNaturalLanguage(arg1:string):Promise<main.LLMProcessResult>;

export function ProcessNaturalLanguageEnhanced(arg1:string):Promise<main.LLMProcessResult>;

export function ProcessNaturalLanguageWithFiles(arg1:string,arg2:Array<string>):Promise<main.LLMProcessResult>;

export function ReloadConfig():Promise<void>;

export function RestartApplication():Promise<void>;

export function SaveConversationMessage(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<void>;

export function SaveTemplate(arg1:Array<string>,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SetInstanceManager(arg1:main.InstanceManager):Promise<void>;

export function SetLLMAPIKey(arg1:string):Promise<void>;

export function SetLLMModel(arg1:string):Promise<void>;

export function SetLLMTimeout(arg1:number):Promise<void>;

export function ShowErrorNotification(arg1:string):Promise<void>;

export function ShowNotification(arg1:string,arg2:string):Promise<void>;

export function ShowSuccessNotification(arg1:string):Promise<void>;

export function ToggleWindow():Promise<void>;

export function UpdateConversationTitle(arg1:string,arg2:string):Promise<void>;

export function UpdateTemplate(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function UploadFile(arg1:string,arg2:string):Promise<main.File>;

export function UseTemplate(arg1:number):Promise<void>;
