// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ExecuteCommand(arg1, arg2) {
  return window['go']['main']['App']['ExecuteCommand'](arg1, arg2);
}

export function ExecuteNaturalLanguageQuery(arg1) {
  return window['go']['main']['App']['ExecuteNaturalLanguageQuery'](arg1);
}

export function ExecuteSQL(arg1) {
  return window['go']['main']['App']['ExecuteSQL'](arg1);
}

export function ExportToExcel(arg1) {
  return window['go']['main']['App']['ExportToExcel'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetInstallationInfo() {
  return window['go']['main']['App']['GetInstallationInfo']();
}

export function GetQueryHistory() {
  return window['go']['main']['App']['GetQueryHistory']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetTableColumns(arg1) {
  return window['go']['main']['App']['GetTableColumns'](arg1);
}

export function GetTableData(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableData'](arg1, arg2, arg3);
}

export function GetTableList() {
  return window['go']['main']['App']['GetTableList']();
}

export function GetTableSchema(arg1) {
  return window['go']['main']['App']['GetTableSchema'](arg1);
}

export function GetUploadedFiles() {
  return window['go']['main']['App']['GetUploadedFiles']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ProcessNaturalLanguage(arg1) {
  return window['go']['main']['App']['ProcessNaturalLanguage'](arg1);
}

export function RestartApplication() {
  return window['go']['main']['App']['RestartApplication']();
}

export function SetInstanceManager(arg1) {
  return window['go']['main']['App']['SetInstanceManager'](arg1);
}

export function SetLLMAPIKey(arg1) {
  return window['go']['main']['App']['SetLLMAPIKey'](arg1);
}

export function UploadFile(arg1, arg2) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2);
}
