import { createCipheriv, createDecipheriv, createHash, randomBytes, randomUUID, verify } from "node:crypto";
import { existsSync, readFileSync, readdirSync, rmSync } from "node:fs";
import { join } from "node:path";
import {
  canonicalJson,
  hubAuditPageSchema, parseHubAppliedObjectReceipt, parseHubAppliedObjectReceipts, parseHubApplyRemoteObjectInput, parseHubBootstrapRequest, parseHubBootstrapResult, parseHubConnectionInput, parseHubConnectionProfile, parseHubStoredConnection, parseHubStoredCredentials, parseHubStoredInbox, parseHubStoredOutbox, parseHubSyncCatalog, parseHubSyncCursor, parseLocalSyncQueue, parseLocalSyncedObjectPreview, parseLocalSyncedObjects, parseSyncPullPackage, parseSyncPushOperation, parseSyncPushResult, parseWorkflowDefinition,
  type HubAppliedObjectReceipt, type HubApplyRemoteObjectInput, type HubAuditPage, type HubBootstrapRequest, type HubConnectionInput, type HubConnectionProfile, type HubStoredConnection, type HubStoredInbox, type HubStoredOutbox, type HubSyncCatalog, type LocalSyncQueueItem, type LocalSyncedObject, type LocalSyncedObjectPreview, type SyncObjectVersion, type SyncPushOperation, type WorkflowDefinition,
} from "@bubu/contracts";
import { assertHubPermission } from "@bubu/product-core";
import type { CredentialCipher } from "./provider-store.js";
import { fetchResolvedPublicTarget, resolvePublicRemoteTarget } from "./remote-network.js";
import { atomicPrivateWrite, preparePrivateDirectory } from "./secure-files.js";
import { startNonOverlappingScheduler } from "./non-overlapping-scheduler.js";

interface Options { readonly directory: string; readonly cipher: CredentialCipher; readonly fetchImpl?: typeof fetch; readonly resolveTarget?: (url: string) => Promise<readonly string[]>; readonly now?: () => Date; readonly newId?: () => string; readonly newOperationId?: () => string }
export interface HubSyncService {
  profile(): HubConnectionProfile | null; configure(value: unknown): HubConnectionProfile; bootstrap(value: unknown): Promise<HubConnectionProfile>; disconnect(): void;
  queueWorkflow(value: unknown): LocalSyncQueueItem; queue(): readonly LocalSyncQueueItem[]; flush(): Promise<readonly LocalSyncQueueItem[]>;
  queueDelete(objectId: string, objectKind: SyncPushOperation["objectKind"]): LocalSyncQueueItem; resolveConflict(queueId: string, decision: "accept-remote" | "retry-local"): LocalSyncQueueItem;
  pull(): Promise<readonly LocalSyncedObject[]>; incoming(): readonly LocalSyncedObject[]; inspectIncoming(objectId: string, version: number): LocalSyncedObjectPreview;
  prepareWorkflowApplication(value: unknown): { readonly selection: HubApplyRemoteObjectInput; readonly definition: WorkflowDefinition; readonly object: LocalSyncedObject; readonly contentSha256: string; readonly existingReceipt: HubAppliedObjectReceipt | null };
  recordWorkflowApplication(value: { readonly selection: HubApplyRemoteObjectInput; readonly localWorkflowVersion: number; readonly localDisposition: HubAppliedObjectReceipt["localDisposition"] }): HubAppliedObjectReceipt; applications(): readonly HubAppliedObjectReceipt[];
  audit(): Promise<{ readonly page: HubAuditPage; readonly verified: boolean }>;
}
const sha256 = (value: string | Buffer) => createHash("sha256").update(value).digest("hex");
const encryptContent = (keyValue: string, contentJson: string) => { const key = Buffer.from(keyValue, "base64url"); const nonce = randomBytes(12); const cipher = createCipheriv("aes-256-gcm", key, nonce); const encrypted = Buffer.concat([cipher.update(contentJson, "utf8"), cipher.final(), cipher.getAuthTag()]); const ciphertext = encrypted.toString("base64url"); return { algorithm: "aes-256-gcm" as const, keyId: sha256(key).slice(0, 32), nonce: nonce.toString("base64url"), ciphertext, contentSha256: sha256(ciphertext) }; };
const decryptContent = (keyValue: string, object: SyncObjectVersion) => { if (!object.payload) throw new Error("Deleted synced objects have no content"); const bytes = Buffer.from(object.payload.ciphertext, "base64url"); if (sha256(object.payload.ciphertext) !== object.payload.contentSha256 || bytes.length < 17) throw new Error("Synced object ciphertext digest is invalid"); const decipher = createDecipheriv("aes-256-gcm", Buffer.from(keyValue, "base64url"), Buffer.from(object.payload.nonce, "base64url")); decipher.setAuthTag(bytes.subarray(-16)); return Buffer.concat([decipher.update(bytes.subarray(0, -16)), decipher.final()]).toString("utf8"); };

export function createHubSyncService(options: Options): HubSyncService {
  preparePrivateDirectory(options.directory); const outboxDirectory = join(options.directory, "outbox"); const inboxDirectory = join(options.directory, "inbox"); preparePrivateDirectory(outboxDirectory); preparePrivateDirectory(inboxDirectory);
  const connectionPath = join(options.directory, "connection.json"); const catalogPath = join(options.directory, "catalog.json"); const cursorPath = join(options.directory, "cursor.json"); const applicationsPath = join(options.directory, "applications.json"); const now = options.now ?? (() => new Date()); const newId = options.newId ?? (() => randomBytes(16).toString("hex")); const newOperationId = options.newOperationId ?? randomUUID; const resolveTarget = options.resolveTarget ?? resolvePublicRemoteTarget;
  const send = async (url: string, init: RequestInit) => { const addresses = await resolveTarget(url); return options.fetchImpl ? options.fetchImpl(url, { ...init, redirect: "manual" }) : fetchResolvedPublicTarget(url, addresses, init); };
  let connection = existsSync(connectionPath) ? readFileSync(connectionPath, "utf8") : undefined; const outbox = new Map<string, HubStoredOutbox>(); const inbox = new Map<string, HubStoredInbox>(); let catalog: HubSyncCatalog = existsSync(catalogPath) ? parseHubSyncCatalog(JSON.parse(readFileSync(catalogPath, "utf8")) as unknown) : {}; let cursor = existsSync(cursorPath) ? parseHubSyncCursor(JSON.parse(readFileSync(cursorPath, "utf8")) as unknown) : 0; let applicationReceipts = existsSync(applicationsPath) ? parseHubAppliedObjectReceipts(JSON.parse(readFileSync(applicationsPath, "utf8")) as unknown) : [];
  for (const file of readdirSync(outboxDirectory)) { if (!file.endsWith(".json")) throw new Error("Hub outbox contains an unknown file"); const parsed = parseHubStoredOutbox(JSON.parse(readFileSync(join(outboxDirectory, file), "utf8")) as unknown); if (parsed.public.id !== file.slice(0, -5)) throw new Error("Hub outbox identifier is inconsistent"); const stored = parsed.public.status === "syncing" ? parseHubStoredOutbox({ ...parsed, public: { ...parsed.public, status: "pending", errorCode: "RESTART_RECOVERY" } }) : parsed; outbox.set(stored.public.id, stored); }
  for (const file of readdirSync(inboxDirectory)) { if (!file.endsWith(".json")) throw new Error("Hub inbox contains an unknown file"); const stored = parseHubStoredInbox(JSON.parse(readFileSync(join(inboxDirectory, file), "utf8")) as unknown); inbox.set(`${stored.object.objectId}:${stored.object.objectVersion}`, stored); }
  const record = (): HubStoredConnection | undefined => connection ? parseHubStoredConnection(JSON.parse(connection) as unknown) : undefined; const credentials = () => { const value = record(); if (!value) throw new Error("Hub is not configured"); return parseHubStoredCredentials(JSON.parse(options.cipher.decrypt(Buffer.from(value.encryptedCredentials, "base64"))) as unknown); };
  const persistConnection = (input: HubConnectionInput) => { if (!options.cipher.isEncryptionAvailable()) throw new Error("Credential encryption is unavailable"); const profile = parseHubConnectionProfile({ baseUrl: input.baseUrl, tenantId: input.tenantId, deviceId: input.deviceId, role: input.role, configured: true, encryptionAvailable: true }); const encryptedCredentials = options.cipher.encrypt(JSON.stringify({ deviceToken: input.deviceToken, contentKey: input.contentKey, auditVerificationKey: input.auditVerificationKey })).toString("base64"); const stored = parseHubStoredConnection({ version: 1, profile, encryptedCredentials }); connection = `${JSON.stringify(stored, null, 2)}\n`; atomicPrivateWrite(connectionPath, connection); return profile; };
  const persistOutbox = (value: HubStoredOutbox) => { const stored = parseHubStoredOutbox(value); atomicPrivateWrite(join(outboxDirectory, `${stored.public.id}.json`), `${JSON.stringify(stored, null, 2)}\n`); outbox.set(stored.public.id, stored); return stored.public; };
  const request = async (path: string, value: unknown, authenticated = true, baseUrlOverride?: string) => { const stored = record(); if (!stored && authenticated) throw new Error("Hub is not configured"); const baseUrl = authenticated ? stored!.profile.baseUrl : baseUrlOverride; if (!baseUrl) throw new Error("Hub URL is required"); const target = new URL(path, baseUrl).toString(); const response = await send(target, { method: "POST", headers: { "content-type": "application/json", accept: "application/json", ...(authenticated ? { authorization: `Bearer ${credentials().deviceToken}` } : {}) }, body: JSON.stringify(value), signal: AbortSignal.timeout(15_000) }); if (response.status >= 300 && response.status < 400) throw new Error("Hub redirects are not accepted"); const text = await response.text(); if (text.length > 512 * 1024) throw new Error("Hub response exceeds 512 KiB"); if (!response.ok) throw new Error(`Hub request failed with HTTP ${response.status}`); return JSON.parse(text) as unknown; };
  const service: HubSyncService = {
    profile: () => record()?.profile ?? null,
    configure(value) { return persistConnection(parseHubConnectionInput(value)); },
    async bootstrap(value) { const input = parseHubBootstrapRequest(value); const result = parseHubBootstrapResult(await request("/v1/bootstrap", { tenantName: input.tenantName, ownerName: input.ownerName, deviceName: input.deviceName }, false, input.baseUrl)); return persistConnection({ baseUrl: input.baseUrl, tenantId: result.tenant.id, deviceId: result.device.id, role: result.member.role, deviceToken: result.deviceToken, contentKey: randomBytes(32).toString("base64url"), auditVerificationKey: result.auditVerificationKey }); },
    disconnect() { connection = undefined; rmSync(connectionPath, { force: true }); },
    queueWorkflow(value) { const definition = parseWorkflowDefinition(value); const profile = record()?.profile; if (!profile) throw new Error("Hub is not configured"); assertHubPermission(profile.role, "sync:write"); const contentJson = JSON.stringify(definition); if (Buffer.byteLength(contentJson) > 256 * 1024) throw new Error("Workflow sync object exceeds 256 KiB"); const contentSha256 = sha256(contentJson); const current = catalog[definition.id]; const existing = [...outbox.values()].find(({ operation, plaintextContentSha256 }) => operation.objectId === definition.id && plaintextContentSha256 === contentSha256); if (existing) return existing.public; const objectVersion = (current?.objectVersion ?? 0) + 1; const operation = parseSyncPushOperation({ schemaVersion: 1, operationId: newOperationId(), tenantId: profile.tenantId, deviceId: profile.deviceId, objectId: definition.id, objectKind: "workflow-definition", baseVersion: current?.objectVersion ?? null, objectVersion, deleted: false, payload: encryptContent(credentials().contentKey, contentJson), createdAt: now().toISOString() }); const item = parseLocalSyncQueue([{ id: newId(), objectId: definition.id, objectKind: "workflow-definition", objectVersion, status: "pending", attempts: 0, createdAt: now().toISOString(), completedAt: null, errorCode: null, conflict: null }])[0]!; return persistOutbox({ public: item, operation, plaintextContentSha256: contentSha256 }); },
    queueDelete(objectId, objectKind) { const profile = record()?.profile; if (!profile) throw new Error("Hub is not configured"); assertHubPermission(profile.role, "sync:write"); const current = catalog[objectId]; if (!current) throw new Error("Only a locally accepted synced object can be deleted"); const operation = parseSyncPushOperation({ schemaVersion: 1, operationId: newOperationId(), tenantId: profile.tenantId, deviceId: profile.deviceId, objectId, objectKind, baseVersion: current.objectVersion, objectVersion: current.objectVersion + 1, deleted: true, payload: null, createdAt: now().toISOString() }); const item = parseLocalSyncQueue([{ id: newId(), objectId, objectKind, objectVersion: operation.objectVersion, status: "pending", attempts: 0, createdAt: now().toISOString(), completedAt: null, errorCode: null, conflict: null }])[0]!; return persistOutbox({ public: item, operation, plaintextContentSha256: "deleted" }); },
    resolveConflict(queueId, decision) { const stored = outbox.get(queueId); if (!stored || stored.public.status !== "conflict" || !stored.public.conflict) throw new Error("Sync conflict does not exist"); if (decision === "accept-remote") return persistOutbox({ ...stored, public: { ...stored.public, status: "discarded", completedAt: now().toISOString(), errorCode: "REMOTE_VERSION_ACCEPTED" } }); const currentVersion = stored.public.conflict.currentVersion; const operation = parseSyncPushOperation({ ...stored.operation, operationId: newOperationId(), baseVersion: currentVersion, objectVersion: (currentVersion ?? 0) + 1, createdAt: now().toISOString() }); return persistOutbox({ ...stored, operation, public: { ...stored.public, objectVersion: operation.objectVersion, status: "pending", attempts: 0, completedAt: null, errorCode: null, conflict: null } }); },
    queue: () => parseLocalSyncQueue([...outbox.values()].map(({ public: item }) => item).sort((left, right) => right.createdAt.localeCompare(left.createdAt))),
    async flush() { const profile = record()?.profile; if (!profile) throw new Error("Hub is not configured"); assertHubPermission(profile.role, "sync:write"); for (const stored of outbox.values()) { if (stored.public.status !== "pending" && !(stored.public.status === "failed" && stored.public.attempts < 3)) continue; const syncing = { ...stored.public, status: "syncing" as const, attempts: stored.public.attempts + 1, errorCode: null }; persistOutbox({ ...stored, public: syncing }); try { const result = parseSyncPushResult(await request("/v1/sync/push", stored.operation)); if (result.status === "conflict") persistOutbox({ ...stored, public: { ...syncing, status: "conflict", completedAt: now().toISOString(), errorCode: "VERSION_CONFLICT", conflict: result } }); else { catalog = parseHubSyncCatalog({ ...catalog, [stored.operation.objectId]: { objectVersion: result.objectVersion, contentSha256: stored.plaintextContentSha256 } }); atomicPrivateWrite(catalogPath, `${JSON.stringify(catalog, null, 2)}\n`); persistOutbox({ ...stored, public: { ...syncing, status: "succeeded", completedAt: now().toISOString(), conflict: null } }); } } catch { persistOutbox({ ...stored, public: { ...syncing, status: syncing.attempts >= 3 ? "failed" : "pending", completedAt: syncing.attempts >= 3 ? now().toISOString() : null, errorCode: "HUB_UNAVAILABLE", conflict: null } }); } } return service.queue(); },
    async pull() { const profile = record()?.profile; if (!profile) throw new Error("Hub is not configured"); assertHubPermission(profile.role, "sync:read"); let hasMore = true; while (hasMore) { const page = parseSyncPullPackage(await request("/v1/sync/pull", { schemaVersion: 1, tenantId: profile.tenantId, deviceId: profile.deviceId, afterSequence: cursor, limit: 100 })); for (const object of page.objects) { const stored = parseHubStoredInbox({ object, receivedAt: now().toISOString() }); atomicPrivateWrite(join(inboxDirectory, `${object.objectId}-${object.objectVersion}.json`), `${JSON.stringify(stored, null, 2)}\n`); inbox.set(`${object.objectId}:${object.objectVersion}`, stored); } cursor = parseHubSyncCursor(page.nextSequence); atomicPrivateWrite(cursorPath, `${JSON.stringify(cursor)}\n`); hasMore = page.hasMore; } return service.incoming(); },
    incoming: () => parseLocalSyncedObjects([...inbox.values()].map(({ object, receivedAt }) => ({ objectId: object.objectId, objectKind: object.objectKind, objectVersion: object.objectVersion, sequence: object.sequence, deleted: object.deleted, receivedAt })).sort((left, right) => right.sequence - left.sequence)),
    inspectIncoming(objectId, version) { const stored = inbox.get(`${objectId}:${version}`); if (!stored) throw new Error("Synced object version does not exist"); const contentJson = decryptContent(credentials().contentKey, stored.object); if (stored.object.objectKind === "workflow-definition") parseWorkflowDefinition(JSON.parse(contentJson) as unknown); return parseLocalSyncedObjectPreview({ object: service.incoming().find((object) => object.objectId === objectId && object.objectVersion === version), contentJson, contentSha256: sha256(contentJson) }); },
    prepareWorkflowApplication(value) { const selection = parseHubApplyRemoteObjectInput(value); const stored = inbox.get(`${selection.objectId}:${selection.objectVersion}`); if (!stored) throw new Error("Synced object version does not exist"); if (stored.object.deleted) throw new Error("Remote tombstones cannot be applied as workflows"); if (stored.object.objectKind !== "workflow-definition") throw new Error("Only remote workflow definitions can be applied"); const contentJson = decryptContent(credentials().contentKey, stored.object); const contentSha256 = sha256(contentJson); if (contentSha256 !== selection.expectedContentSha256) throw new Error("Reviewed remote content digest changed"); const definition = parseWorkflowDefinition(JSON.parse(contentJson) as unknown); const object = service.incoming().find((candidate) => candidate.objectId === selection.objectId && candidate.objectVersion === selection.objectVersion); if (!object) throw new Error("Synced object catalog is inconsistent"); const existingReceipt = applicationReceipts.find((receipt) => receipt.objectId === selection.objectId && receipt.objectVersion === selection.objectVersion && receipt.contentSha256 === contentSha256) ?? null; return { selection, definition, object, contentSha256, existingReceipt }; },
    recordWorkflowApplication(value) { const prepared = service.prepareWorkflowApplication(value.selection); if (prepared.existingReceipt) return prepared.existingReceipt; const receipt = parseHubAppliedObjectReceipt({ schemaVersion: 1, objectId: prepared.object.objectId, objectKind: "workflow-definition", objectVersion: prepared.object.objectVersion, remoteSequence: prepared.object.sequence, contentSha256: prepared.contentSha256, localWorkflowVersion: value.localWorkflowVersion, localDisposition: value.localDisposition, appliedAt: now().toISOString() }); applicationReceipts = parseHubAppliedObjectReceipts([...applicationReceipts, receipt]); atomicPrivateWrite(applicationsPath, `${JSON.stringify(applicationReceipts, null, 2)}\n`); return receipt; },
    applications: () => parseHubAppliedObjectReceipts(applicationReceipts),
    async audit() { const stored = record(); if (!stored) throw new Error("Hub is not configured"); assertHubPermission(stored.profile.role, "audit:read"); const target = new URL("/v1/audit", stored.profile.baseUrl).toString(); const response = await send(target, { headers: { authorization: `Bearer ${credentials().deviceToken}` }, signal: AbortSignal.timeout(15_000) }); if (response.status >= 300 && response.status < 400) throw new Error("Hub redirects are not accepted"); const text = await response.text(); if (text.length > 512 * 1024) throw new Error("Hub response exceeds 512 KiB"); if (!response.ok) throw new Error(`Hub request failed with HTTP ${response.status}`); const page = hubAuditPageSchema.parse(JSON.parse(text) as unknown); const publicKey = Buffer.from(credentials().auditVerificationKey, "base64url").toString(); let previousHash = "0".repeat(64); let verified = true; for (const event of page.events) { const { eventHash, signature, ...unsigned } = event; if (event.previousHash !== previousHash || sha256(canonicalJson(unsigned)) !== eventHash || !verify(null, Buffer.from(eventHash, "hex"), publicKey, Buffer.from(signature, "hex"))) { verified = false; break; } previousHash = eventHash; } return { page, verified }; },
  }; return service;
}

export function startHubSyncScheduler(service: HubSyncService, onError: (error: unknown) => void = () => undefined): () => void { return startNonOverlappingScheduler({ intervalMilliseconds: 30_000, task: () => service.flush(), canRun: () => service.profile() !== null, onError }); }
