import { parseHubApplyRemoteObjectInput, type HubAppliedObjectReceipt, type WorkflowDefinitionInput } from "@bubu/contracts";
import { decideRemoteWorkflowApplication } from "@bubu/product-core";
import type { HubSyncService } from "./hub-sync-service.js";
import type { SidecarSupervisor } from "./sidecars.js";

type ApplicationSidecars = Pick<SidecarSupervisor, "getConversationByID" | "listWorkflows" | "saveWorkflow">;
export async function applyRemoteWorkflowObject(hub: HubSyncService, sidecars: ApplicationSidecars, value: unknown): Promise<HubAppliedObjectReceipt> {
  const selection = parseHubApplyRemoteObjectInput(value); const prepared = hub.prepareWorkflowApplication(selection); const thread = await sidecars.getConversationByID(prepared.definition.threadId); const decision = decideRemoteWorkflowApplication({ objectKind: prepared.object.objectKind, deleted: prepared.object.deleted, expectedContentSha256: selection.expectedContentSha256, actualContentSha256: prepared.contentSha256, localTargetExists: thread !== null, localThreadMatches: thread?.target.kind === prepared.definition.target.kind && thread.target.id === prepared.definition.target.id, alreadyApplied: prepared.existingReceipt !== null }); if (decision.status === "blocked") throw new Error(`Remote workflow application blocked: ${decision.code}`); if (prepared.existingReceipt) return prepared.existingReceipt;
  const input: WorkflowDefinitionInput = { id: prepared.definition.id, name: prepared.definition.name, target: prepared.definition.target, threadId: prepared.definition.threadId, trigger: prepared.definition.trigger, timeoutMs: prepared.definition.timeoutMs, steps: prepared.definition.steps }; const existing = (await sidecars.listWorkflows(input.target)).find(({ id }) => id === input.id); const comparable = (workflow: typeof prepared.definition | WorkflowDefinitionInput) => JSON.stringify({ id: workflow.id, name: workflow.name, target: workflow.target, threadId: workflow.threadId, trigger: workflow.trigger, timeoutMs: workflow.timeoutMs, steps: workflow.steps }); const identical = existing !== undefined && comparable(existing) === comparable(input); if (existing && !identical && selection.decision !== "replace-reviewed-workflow") throw new Error("Remote workflow application blocked: LOCAL_WORKFLOW_DIFFERS"); const saved = identical ? existing : await sidecars.saveWorkflow(input); return hub.recordWorkflowApplication({ selection, localWorkflowVersion: saved.version, localDisposition: identical ? "identical" : existing ? "replaced" : "created" });
}
