import { describe, expect, it, vi } from "vitest";
import type { HubSyncService } from "./hub-sync-service.js";
import { applyRemoteWorkflowObject } from "./hub-application-service.js";

const digest = "d".repeat(64); const objectId = "a".repeat(32); const threadId = "c".repeat(32); const target = { kind: "dataset" as const, id: "b".repeat(32) }; const definition = { id: objectId, version: 1, name: "Remote reviewed workflow", target, threadId, trigger: { kind: "manual" as const }, timeoutMs: 60_000, steps: [{ id: "query", kind: "dataset-query" as const, plan: { schemaVersion: 1 as const, datasetId: target.id, versionId: "e".repeat(32), purpose: "Totals", dimensions: ["Region"], measures: [{ operation: "count" as const }], filters: [], sort: [], limit: 10 }, maxAttempts: 1 }], createdAt: "2026-07-29T00:00:00Z", updatedAt: "2026-07-29T00:00:00Z", nextDueAt: null };
const selection = { objectId, objectVersion: 1, expectedContentSha256: digest, decision: "apply-if-absent-or-identical" as const }; const receipt = { schemaVersion: 1 as const, objectId, objectKind: "workflow-definition" as const, objectVersion: 1, remoteSequence: 1, contentSha256: digest, localWorkflowVersion: 2, localDisposition: "created" as const, appliedAt: "2026-07-29T00:00:00Z" };
function hub(existingReceipt: typeof receipt | null = null): HubSyncService { return { prepareWorkflowApplication: () => ({ selection, definition, object: { objectId, objectKind: "workflow-definition", objectVersion: 1, sequence: 1, deleted: false, receivedAt: "2026-07-29T00:00:00Z" }, contentSha256: digest, existingReceipt }), recordWorkflowApplication: () => receipt } as unknown as HubSyncService; }
describe("reviewed remote workflow application", () => {
  it("saves only after the exact target thread exists and records the local version", async () => { const saveWorkflow = vi.fn(async () => ({ ...definition, version: 2 })); const sidecars = { getConversationByID: vi.fn(async () => ({ target })), listWorkflows: vi.fn(async () => []), saveWorkflow }; await expect(applyRemoteWorkflowObject(hub(), sidecars as never, selection)).resolves.toEqual(receipt); expect(saveWorkflow).toHaveBeenCalledOnce(); });
  it("fails closed on a mismatched local thread and reuses an existing receipt idempotently", async () => { const sidecars = { getConversationByID: vi.fn(async () => ({ target: { kind: "dataset", id: "f".repeat(32) } })), listWorkflows: vi.fn(), saveWorkflow: vi.fn() }; await expect(applyRemoteWorkflowObject(hub(), sidecars as never, selection)).rejects.toThrow("LOCAL_THREAD_MISMATCH"); expect(sidecars.saveWorkflow).not.toHaveBeenCalled(); sidecars.getConversationByID.mockResolvedValue({ target }); await expect(applyRemoteWorkflowObject(hub(receipt), sidecars as never, selection)).resolves.toEqual(receipt); expect(sidecars.listWorkflows).not.toHaveBeenCalled(); });
  it("never replaces different local content without a separate explicit decision", async () => { const local = { ...definition, version: 4, name: "Local different workflow" }; const saveWorkflow = vi.fn(async () => ({ ...definition, version: 5 })); const sidecars = { getConversationByID: vi.fn(async () => ({ target })), listWorkflows: vi.fn(async () => [local]), saveWorkflow }; await expect(applyRemoteWorkflowObject(hub(), sidecars as never, selection)).rejects.toThrow("LOCAL_WORKFLOW_DIFFERS"); expect(saveWorkflow).not.toHaveBeenCalled(); const replaced = { ...selection, decision: "replace-reviewed-workflow" as const }; await expect(applyRemoteWorkflowObject(hub(), sidecars as never, replaced)).resolves.toEqual(receipt); expect(saveWorkflow).toHaveBeenCalledOnce(); });
});
